Upgrade to intervantion v3
laravelio/laravel.io pull request #1189
Opened 2024-11-23 13:57 UTC by tauseefsshah

This PR aims to fix #1187  using laravel's `response()` method.

2024-12-01 15:37 UTC, tauseefsshah commented
@driesvints The functionality works but I am not able fix the test that I wrote. The test runs fine on my local (MacOS + Herd) but fails on github actions. I suspect it's because of different environments or something similar but not sure. Should I remove the test for now so you can merge this PR?

2024-12-06 15:02 UTC, driesvints commented
@tauseefsshah heya sorry for the long wait here.. could you maybe rebase this PR and fix the conflicts before I review? Thanks!

2024-12-06 15:03 UTC, driesvints requested changes
Looks real good overall!

2024-12-06 15:03 UTC, driesvints commented on package.json
> +        "pixelmatch": "^5.0.0"
Move this to devdependencies

2024-12-06 15:03 UTC, driesvints commented on app/Jobs/GenerateSocialShareImage.php
> +        )->header('Content-Type', 'image/png');
Would be good if we could cache this somehow as well.

2024-12-06 18:18 UTC, tauseefsshah commented
Hey @driesvints 👋 Made the following updates:

1. Rebased the branch with the latest `main` branch
2. Moved `pixelmatch` to devDeps 
3. Added cache for the response using Laravels `Cache` with a ttl set to 24 hours

Please review now and also what about the test I wrote? It's still failing on github actions. Should I skip/remove the test for now?

2025-02-28 13:56 UTC, merged

2025-02-28 13:57 UTC, driesvints commented
I disabled that test for now. Couldn't figure it out either but it's running locally and I verified this approach works.

Thanks a bunch for your work here @tauseefsshah! Sorry it took me so long to review this.

2025-03-07 07:35 UTC, driesvints commented
I now see the text is just a little too high. Could you adjust that maybe @tauseefsshah ?

<img width="580" alt="Scherm­afbeelding 2025-03-07 om 08 33 26" src="https://github.com/user-attachments/assets/a976bbd7-5d15-4e8a-b30a-6c81ae1c784c" />

Should be more like this:

<img width="591" alt="Scherm­afbeelding 2025-03-07 om 08 35 39" src="https://github.com/user-attachments/assets/94695efe-f768-4b5e-aa46-a1c5b723ec9d" />

2025-03-08 06:13 UTC, tauseefsshah commented
Hey @driesvints 
Yes let me fix this and raise a PR :)

2025-03-16 16:47 UTC, tauseefsshah commented
Hey @driesvints Have raised a PR #1262 to fix the positioning