Implement profile page
laravelio/laravel.io pull request #673
Opened 2021-08-25 20:21 UTC by joedixon

<img width="372" alt="Screenshot 2021-08-27 at 16 24 31" src="https://user-images.githubusercontent.com/3438564/131151376-36959917-5a6b-4821-a395-9deaf90049c2.png">

<img width="1440" alt="Screenshot 2021-08-27 at 16 24 14" src="https://user-images.githubusercontent.com/3438564/131151380-5ac24d54-4d67-42a6-87fd-a332d24e219c.png">

<img width="1439" alt="Screenshot 2021-08-27 at 16 27 28" src="https://user-images.githubusercontent.com/3438564/131151654-f715a586-3d69-471d-ab02-9a738c9a61a2.png">

<img width="1440" alt="Screenshot 2021-08-27 at 16 23 56" src="https://user-images.githubusercontent.com/3438564/131151385-2e270d36-bf64-4591-aed3-7b4f867fce65.png">

2021-08-28 10:04 UTC, driesvints requested changes
Maybe we can do something fun for these places where there's no content?

![Screen Shot 2021-08-28 at 11 51 21](https://user-images.githubusercontent.com/594614/131214098-37c258eb-0d2c-4bb7-822a-c76144cdb0eb.jpg)

Something like...

![Screen Shot 2021-08-28 at 11 52 59](https://user-images.githubusercontent.com/594614/131214115-9a5a07f6-e82b-4e45-9684-5f90a7267110.jpg)

I think there are some free artwork platforms that we could consult.

I also realized that the list of replies on the user profile don't make much sense atm. You can't see to which thread they belong. I think we need to slightly redesign these. They also shouldn't be interactive (no clickable likes, solution chosing, no dropdown menu). Just clickable so you can link to them in a thread.

![Screen Shot 2021-08-28 at 12 01 21](https://user-images.githubusercontent.com/594614/131214372-fa0a58d5-8128-4bee-a0c2-8c511ac09ef4.jpg)

2021-08-30 20:32 UTC, joedixon commented on resources/svg/hammer.svg
> +<svg class="w-64 h-64" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 613 613" enable-background="new 0 0 613 613" xml:space=
Oops, this is how I pasted it from the blade ui kit icon search and forgot to remove.

2021-09-01 19:16 UTC, joedixon commented
> Maybe we can do something fun for these places where there's no content?

I think this is a nice idea, but are you happy if we add it as an issue for now while we find some artwork we like?

2021-09-01 19:17 UTC, joedixon commented
New reply component for the profile page\

<img width="1318" alt="Screenshot 2021-09-01 at 20 07 36" src="https://user-images.githubusercontent.com/3438564/131730597-a74e579f-7f67-4e3b-a5a4-d9fdca93a7b4.png">

2021-09-02 10:54 UTC, driesvints commented
@joedixon for the empty states. Can you maybe use the "simple" component from https://tailwindui.com/components/application-ui/feedback/empty-states ?

2021-09-02 18:58 UTC, joedixon commented
<img width="1084" alt="Screenshot 2021-09-02 at 19 56 32" src="https://user-images.githubusercontent.com/3438564/131901013-a62aa170-0fd4-4ad0-a02f-930bedcb772d.png">

<img width="1367" alt="Screenshot 2021-09-02 at 19 56 24" src="https://user-images.githubusercontent.com/3438564/131901020-1be0602c-23ff-452c-b9fb-0be77c36e7a9.png">

2021-09-03 15:00 UTC, merged