Implement editor from designs
laravelio/laravel.io pull request #707
Opened 2021-10-18 19:25 UTC by joedixon

This PR implements the new designs for the editor which resolves #690. Additionally, it leverages Livewire to add a new `Preview` feature as suggested by @tvbeek and so resolves #706. This allows users to write their thread, reply or article and preview it before saving.

<img width="1279" alt="Screenshot 2021-10-31 at 20 49 22" src="https://user-images.githubusercontent.com/3438564/139600818-402991a9-8a84-4eec-bae5-c311a0c393ad.png">

https://user-images.githubusercontent.com/3438564/139600822-b5287df8-97a6-4a29-b3d9-a479a6bebd64.mov

<img width="1285" alt="Screenshot 2021-10-31 at 20 45 27" src="https://user-images.githubusercontent.com/3438564/139600825-911b92b2-1259-4e0a-91ee-94cb9a1af4bb.png">

<img width="930" alt="Screenshot 2021-10-31 at 20 45 08" src="https://user-images.githubusercontent.com/3438564/139600826-652852d7-36da-47af-8473-5c03de62fe37.png">

2021-10-31 20:40 UTC, joedixon commented on resources/js/editor.js
> -window.expand = (element, minHeight) => {
This is now handled by Alpine and Tailwind.

2021-10-31 20:40 UTC, joedixon commented on tailwind.config.js
> +    mode: 'jit',
🔥

2021-10-31 20:56 UTC, joedixon commented on resources/views/articles/_form.blade.php
> +            <x-editor :content="isset($article) ? $article->body() : null"/>
I couldn't use this as the variable wasn't null, but instead, there were certain scenarios where it didn't exist. However, I got around this by extracting a blade component and defaulting to `null`.

2021-11-01 09:40 UTC, driesvints requested changes
Let's sneak in https://github.com/laravelio/laravel.io/issues/674 as well.

2021-11-02 21:22 UTC, joedixon commented
This also now resolve #674

2021-11-03 18:49 UTC, merged