update: top article submitters widget
laravelio/laravel.io pull request #714
Opened 2021-10-30 14:50 UTC by faissaloux

resolves #713

2021-11-02 21:21 UTC, joedixon commented
Hi @faissaloux,

Thanks for the contribution. Would you mind posting a screenshot of the update?

2021-11-02 22:43 UTC, faissaloux commented
@joedixon

![Screenshot from 2021-11-02 23-42-30](https://user-images.githubusercontent.com/60013703/139961814-1d84e7d8-b2c0-4d88-ab7a-3a7b6ae02deb.png)

2021-11-03 10:02 UTC, driesvints commented
Seems like the avatars don't align properly with the moderator widget. Can you check into making them align the same? On the forum overview page they align the same.

2021-11-03 10:53 UTC, faissaloux commented
@driesvints fixed

![Screenshot from 2021-11-03 11-52-54](https://user-images.githubusercontent.com/60013703/140047990-8ebae44c-4052-4b26-92c4-2f756b6f9be9.png)

2021-11-03 18:57 UTC, driesvints commented on app/Http/Controllers/Articles/ArticlesController.php
> +        $topSubmitters = User::mostSubmitsInLastDays(365)->take(5)->get();
Rename this to `$topAuthors` and use that terminology in the subsequent views as well.

2021-11-03 18:57 UTC, driesvints commented on resources/views/articles/index.blade.php
> +                        Top article submitters
```suggestion
                        Top authors
```

2021-11-04 11:10 UTC, joedixon requested changes
Just a small change to the scope name and then I think we're good to go. Thanks!

2021-11-04 11:10 UTC, joedixon commented on app/Http/Controllers/Articles/ArticlesController.php
> +        $topAuthors = User::mostSubmitsInLastDays(365)->take(5)->get();
```suggestion
        $topAuthors = User::mostSubmissionsInLastDays(365)->take(5)->get();
```

2021-11-04 11:10 UTC, joedixon commented on app/Models/User.php
> +    public function scopeMostSubmits(Builder $query, int $inLastDays = null)
```suggestion
    public function scopeMostSubmissions(Builder $query, int $inLastDays = null)
```

2021-11-04 11:10 UTC, joedixon commented on app/Models/User.php
> +    public function scopeMostSubmitsInLastDays(Builder $query, int $days)
```suggestion
    public function scopeMostSubmissionsInLastDays(Builder $query, int $days)
```

2021-11-04 11:10 UTC, joedixon commented on app/Models/User.php
> +        return $query->mostSubmits($days);
```suggestion
        return $query->mostSubmissions($days);
```

2021-11-04 11:53 UTC, joedixon approved these changes
This is awesome, thank you!

2021-11-04 11:53 UTC, merged