fix article control buttons
laravelio/laravel.io pull request #731
Opened 2021-11-08 23:36 UTC by faissaloux

resolves #728

https://user-images.githubusercontent.com/60013703/140835062-41a8434d-4ccb-4e37-ad2d-335653468e0e.mp4

2021-11-09 09:46 UTC, driesvints commented
I like this. Can we make all buttons like this? Also pin and delete.

I also think we need different icons for publish and decline. Maybe these two?

Approve: https://blade-ui-kit.com/blade-icons/heroicon-s-check
Decline: https://blade-ui-kit.com/blade-icons/heroicon-s-x

2021-11-12 15:13 UTC, joedixon requested changes
I really like this too, great job. Just a couple of minor formatting tweaks from me.

2021-11-12 15:13 UTC, joedixon commented on resources/views/components/articles/actions.blade.php
> +    x-data="{ hovered:false }"
```suggestion
    x-data="{ hovered: false }"
```

2021-11-12 15:13 UTC, joedixon commented on resources/views/components/articles/actions.blade.php
> +                        <span x-show="hovered === 'pin'">{{ $article->isPinned() ? 'Unpin article' : 'Pin article' }}</span>
```suggestion
                    <span x-show="hovered === 'pin'">{{ $article->isPinned() ? 'Unpin article' : 'Pin article' }}</span>
```

2021-11-12 15:45 UTC, joedixon commented
@driesvints I'm happy with this when you are

2021-11-13 14:11 UTC, merged

2021-11-13 14:11 UTC, driesvints commented
Thanks @faissaloux!

2021-11-13 14:15 UTC, driesvints commented
I just noticed this PR causes a weird issue with buttons expanding on the bottom padding when you hover over them. Can we get that fixed?

2021-11-13 14:18 UTC, faissaloux commented
Yes @driesvints I just noticed the same issue I'll fix it

2021-11-13 14:34 UTC, faissaloux commented
@driesvints #732 fixes this height issue

2021-11-18 07:39 UTC, driesvints commented
@faissaloux I just noticed that I can't seem to click any of the buttons anymore in Safari after this.

2021-11-18 10:16 UTC, joedixon commented
@driesvints fixed here https://github.com/laravelio/laravel.io/pull/747