Refactor all jobs to return 'void'.
laravelio/laravel.io pull request #853
Opened 2022-04-06 18:51 UTC by joelbutcher

### What's changed:

- New [anonymous migration file](database/migrations/2022_04_06_152416_add_uuids_to_tables.php) to add uuids to the following model tables:
  - Articles
  - Threads
  - Replies
- Updates all `Job::handle(...)` methods to return `void`
- Migrates the `CreateApiToken` and `GenerateSocialShareImage ` jobs to an "action" (inspired by Jetstream / Fortify) - semantically this makes sense to me, happy to come up with an alternative, if necessary
- Updates the calling code for all jobs to reflect this.
- Updates tests

2022-04-07 08:01 UTC, driesvints requested changes
This is a great PR @joelbutcher! 👏 

Left a couple of comments.

2022-04-07 08:03 UTC, driesvints requested changes

2022-04-07 08:03 UTC, driesvints commented on database/migrations/2022_04_06_152416_add_uuids_to_tables.php
> +    }
There's no down method needed. We never add those.

2022-04-07 08:03 UTC, driesvints commented on database/migrations/2022_04_06_152416_add_uuids_to_tables.php
> +    ];
I don't think referencing app code is wise in migrations. Let's reference the tables directly.

2022-04-07 09:44 UTC, joelbutcher commented on app/Actions/CreateApiToken.php
> +}
@driesvints what do you want to do in the case for the GenerateSocialShareImage job? Keeping this as a job and adding the void return type to the handle method causes issue unless we use the Cache facade - is that an appropriate solution for you?

2022-04-07 09:49 UTC, driesvints commented on app/Actions/CreateApiToken.php
> +}
How do you mean it will cause issues? Afaik we can just convert it back to a job?

2022-04-07 10:22 UTC, joelbutcher commented on app/Actions/CreateApiToken.php
> +}
@driesvints it's the calling code for the `GenerateSocialShareImage` job that has the issue, coz it returns the resulting created image

2022-04-12 20:13 UTC, joelbutcher commented
@driesvints unsure if you've seen already, so forgive me if you're just extremely busy atm, but this PR is ready for another review from yourself 👍

2022-04-14 08:39 UTC, driesvints commented
Heya, yes I did! But bit short on time sorry.. I'll check into this when I have some time.

2022-04-27 19:23 UTC, merged

2022-04-27 19:24 UTC, driesvints commented
So I did end up creating one action for the generation of the social image. In the end, this is more a service class than a command. Because we don't have a concept of services yet in the portal I thought actions might indeed be a good idea to use them for.

Thanks a lot for this @joelbutcher!

2022-04-27 19:25 UTC, driesvints commented
I forgot to convert the migration to a command... oh well 😅

2022-04-28 07:33 UTC, driesvints commented
Ah no I'm mistaken. We just still need a command to populate the empty columns. Then remove the nullable afterwards.