Mark as spam
laravelio/laravel.io pull request #878
Opened 2022-06-14 07:02 UTC by sawirricardo

Referencing the issue #507 
- User can mark a thread as spam
- Notify moderators after 3 or more user report it as spam

2022-07-06 15:04 UTC, driesvints requested changes
Heya, thanks for your PR! Can you do these changes and rebase with `main` branch?

2022-07-06 15:04 UTC, driesvints commented on app/Notifications/ThreadMarkedAsSpamNotification.php
> +    }
```suggestion
    public function __construct(private Thread $thread)
    {
    }
```

2022-07-08 01:15 UTC, sawirricardo commented on app/Jobs/MarkThreadAsSpam.php
> +class MarkThreadAsSpam implements ShouldQueue
Resolved with commit https://github.com/laravelio/laravel.io/pull/878/commits/626a53bce3b343b489158a3f346a1194d186f3de

2022-07-08 08:45 UTC, driesvints commented
Seems like rebasing went wrong here. Can you resend this in?

2022-07-08 08:45 UTC, closed without merging