Move icon link
laravelio/laravel.io pull request #964
Opened 2023-11-02 18:28 UTC by ilasisi

@driesvints This PR attend to this issue https://github.com/laravelio/laravel.io/issues/962

Attached is the screenshot of how it looks now. Please let me know if there's an adjustment I need to make.

![image](https://github.com/laravelio/laravel.io/assets/24248063/04fd1526-a797-4993-b02e-b2f296097823)

2023-11-03 08:05 UTC, driesvints requested changes
Thank you! Got a few review comments here.

2023-11-03 08:05 UTC, driesvints commented on app/Http/Controllers/Settings/ApiTokenController.php
> +        return redirect()->route('settings.profile')->with('api_token', $plainTextToken);
Can you revert all these changes about the token? They should already be on master.

2023-11-03 08:05 UTC, driesvints commented on app/Jobs/CreateApiToken.php
> +        return $this->user->createToken($this->name)->plainTextToken;
Revert these changes please.

2023-11-03 08:05 UTC, driesvints commented on resources/views/layouts/_nav.blade.php
> +                        </a>
```suggestion
                        </a>

```

2023-11-03 08:05 UTC, driesvints commented on resources/views/layouts/_nav.blade.php
> +                            <span class="sr-only">X (Formerly Twitter)</span>
```suggestion
                            <span class="sr-only">X</span>
```

2023-11-08 15:06 UTC, driesvints commented
Thanks, we got another PR for this: https://github.com/laravelio/laravel.io/pull/975

2023-11-08 15:09 UTC, ilasisi commented
@driesvints sorry just seeing your comments. 

I would be closing the PR right away

2023-11-08 15:09 UTC, closed without merging